<a href="https://colab.research.google.com/github/hirohitoo/BL131TSE/blob/gh-pages/specpanda_241214_dist241217.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Initialize (machine non-specific parameters)

In [ ]:
import pandas as pd # version 0.16.0 or later
import numpy as np
import datetime
from matplotlib import pyplot as plt

def variablename(var):
    return [tpl[0] for tpl in
    filter(lambda x: var is x[1], globals().items())]

def get_df_name(df):
    name =[x for x in globals() if globals()[x] is df][0]
    return name
    #returns df's name to string

def get_df(str0):
    return globals()[str0]
    #returns df

colnames_base=",'epoch','seconds','zom','ch','fy','ref','i1','testfy','ctemp','i0','sc']"
Skiprow='14'
Epoch_offset=2133 #Epoch_132=Epoch_ssrl+2133

Scan_R_dict=[(390,440,'N'),(445,480,'Ti'),(455,490,'Ru'),(510,560,'O'),(620,680,'Mn'),(765,820,'Co'),(835,890,'Ni')]
Norm_L_dict=[(393,395,'N'),(453,454,'Ti'),(520,527,'O')]
Norm_H_dict=[(408,411,'N'),(468,469,'Ti'),(544,546,'O')]

belowedge=[393,395]
aboveedge=[408,411]


import math
stick_width=19.05
SampleX_min=0
SampleZ_min=455.5
R_cen=[(6,0,455.25),(6,0,455.25),(6,0,455.25),(6,0,454)]

def samplename_from_xyzr(df_sample,x,y,z,r):
    RR=r%90
    stick_width=19.05
    #X_cenRR=(df_sample['X_cen'])*math.sin(RR/180*math.pi)-np.sqrt(2)*(stick_width/2-df_sample['Y_cen'])*math.cos((90+45-RR)/180*math.pi)  +1*math.cos((90+45-RR)/180*math.pi) #df_sample['R_cenX']#+df_sample['R_cenX']#-math.sin(15/180*math.pi)*stick_width+SampleX_min
    df_sample['X_minR']=(df_sample['X_min'])*math.sin(RR/180*math.pi)-np.sqrt(2)*(stick_width/2-df_sample['Y_cen'])*math.cos((90+45-RR)/180*math.pi)  +df_sample['R_cenX']*math.cos((90+45-RR)/180*math.pi) #df_sample['R_cenX']#+df_sample['R_cenX']#-math.sin(15/180*math.pi)*stick_width+SampleX_min
    df_sample['X_maxR']=(df_sample['X_max'])*math.sin(RR/180*math.pi)-np.sqrt(2)*(stick_width/2-df_sample['Y_cen'])*math.cos((90+45-RR)/180*math.pi)  +df_sample['R_cenX']*math.cos((90+45-RR)/180*math.pi) #df_sample['R_cenX']#+df_sample['R_cenX']#-math.sin(15/180*math.pi)*stick_width+SampleX_min

    #samplename=df_sample[(df_sample['X_minR'] <= x) & (df_sample['X_maxR']  >= y)  &  (df_sample['Z_min'] <= z) & (df_sample['Z_max']  >= z) &(df_sample['R_min']<= r) & (df_sample['R_max']  >= r)]["name"]
    #samplename=df_sample[(X_minRR <= x) & (X_maxRR  >= y)  &  (df_sample['Z_min'] <= z) & (df_sample['Z_max']  >= z) &(df_sample['R_min']<= r) & (df_sample['R_max']  >= r)]["name"]
    samplename=df_sample[ (df_sample['Z_min'] <= z) & (df_sample['Z_max']  >= z) &(df_sample['R_min']<= r) & (df_sample['R_max']  >= r)]["SAMPLE"]

    if len(samplename)!=0:
        return(samplename.tolist()[0])
    elif z < SampleZ_min:
        return('photodiode')
    else:
        return(None)

def sampleid_from_xyzr(df_sample,x,y,z,r):

    RR=r%90
    stick_width=19.05
    df_sample['X_minR']=(df_sample['X_min'])*math.sin(RR/180*math.pi)-np.sqrt(2)*(stick_width/2-df_sample['Y_cen'])*math.cos((90+45-RR)/180*math.pi)  +df_sample['R_cenX']*math.cos((90+45-RR)/180*math.pi) #df_sample['R_cenX']#+df_sample['R_cenX']#-math.sin(15/180*math.pi)*stick_width+SampleX_min
    df_sample['X_maxR']=(df_sample['X_max'])*math.sin(RR/180*math.pi)-np.sqrt(2)*(stick_width/2-df_sample['Y_cen'])*math.cos((90+45-RR)/180*math.pi)  +df_sample['R_cenX']*math.cos((90+45-RR)/180*math.pi) #df_sample['R_cenX']#+df_sample['R_cenX']#-math.sin(15/180*math.pi)*stick_width+SampleX_min

    #sampleid=df_sample[(df_sample['X_minR'] <= x) & (df_sample['X_maxR']  >= x)  &  (df_sample['Z_min'] <= z) & (df_sample['Z_max']  >= z) &(df_sample['R_min']<= r) & (df_sample['R_max']  >= r)]["Sample_ID"]
    sampleid=df_sample[(df_sample['Z_min'] <= z) & (df_sample['Z_max']  >= z) &(df_sample['R_min']<= r) & (df_sample['R_max']  >= r)]["ID"]

    if len(sampleid)!=0:
        return(sampleid.tolist()[0])
    else:
        return(None)

def scanstring_from_mono132(M0):
    for i in range(len(Scan_R_dict)):
        if ((M0 <= float(Scan_R_dict[i][1])) &  (M0 >= float(Scan_R_dict[i][0]))):
            return(Scan_R_dict[i][2])
    return('')

def normlow_from_scanstring(M0):
    for i in range(len(Norm_L_dict)):
        if ((M0 == (Norm_L_dict[i][2]))):
            return(Norm_L_dict[i][0],Norm_L_dict[i][1])
    return('')
def normhigh_from_scanstring(M0):
    for i in range(len(Norm_H_dict)):
        if ((M0 ==(Norm_H_dict[i][2]))):
            return(Norm_H_dict[i][0],Norm_H_dict[i][1])
    return('')

import os

In [ ]:
normlow_from_scanstring('O')

(520, 525)

# Initiualize (machine specific parameters)

In [ ]:
# This is the configuration to analyze files on Google Drive
# Need to copy data files to MyDrive/SSRL_BL132
from google.colab import drive
drive.mount('/content/gdrive')

home='/content/gdrive/MyDrive/SSRL_BL132/6739/data/'
DirSeparator='/'
os.chdir(home)

Mounted at /content/gdrive

# Specifiy experiment numbers

In [ ]:
experiment=["20241214"] #list
dir = dir+"/pandas"
if not os.path.exists(dir):
    os.makedirs(dir)

Directory structure

20240615/spec/htxs
20240615/htxs_load.mac
20240615/htxscom.csv
20240615/htxssample.csv
20240615/pandas/xas-???.csv
20240615/pandas/df_xyzr.csv
20240615/pandas/df_xas.csv

20240622/spec/htxs
20240622/htxs_load.mac
20240622/htxscom.csv
20240622/htxssample.csv
20240622/pandas/xas-???.csv
20240622/pandas/df_xyzr.csv
20240622/pandas/df_xas.csv

#Post initializaiton check

In [ ]:
os.chdir(dir)
!ls

htxscom.csv	 htxs_external		 htxs_queue2.mac     htxssample.csv  spec	 tmp.mac
htxs_comments	 htxs_load.mac		 htxs_queue.mac      htxs_scans.mac  spec_alias
htxs_config.mac  htxs_load.mac.template  htxs_queue_Sat.mac  pandas	     spec_nobg

#Create Dataframe files (Need to do once)

## Collect sample informaiton

In [ ]:
import subprocess

for _experiment in experiment:
    os.chdir(home+_experiment)
    ! cat spec/htxs |tr -s ' '|grep "#" >htxscom.csv
    ! cat htxs_load.mac |cut -f1 -d"#"|tr -s ' '|grep "htxs_set_sample_info" |  sed -e 's/\t/ /g' |tr -s ' ' > htxssample.csv
os.chdir(home)

## Create sample name DF: df_sample

In [ ]:
#Not needed
colnames_sample=['Sample_C','C0','C1','SAMPLE','leftbot_hor','leftbot_dep','leftbot_ver','righttop_hor','righttop_dep','righttop_ver','C2','C3']
inputfile=home+'20241214/htxssample.csv'
#for _experiment in experiment: inputfile=_experiment+'/htxssample.csv'
df_sample = pd.read_csv(inputfile, names=colnames_sample, header=None,sep=' ')
df_sample['ID']=df_sample['C0']*100+df_sample['C1']

#df_sample['R_min']=((6-df_sample['C0'])%4*90-90+0.5)%360
#df_sample['R_max']=((6-df_sample['C0'])%4*90-0.5)%360  #1 2 3 4 -> 1 4 3 2  (6-N)%4 (6-N)%4 6-N 6-N
df_sample['R_min']=((df_sample['C0'])%4*90-90+0.1)%360
df_sample['R_max']=((df_sample['C0'])%4*90+0.1)%360
df_sample['Z_min']=df_sample['leftbot_ver']+SampleZ_min
df_sample['Z_max']=df_sample['righttop_ver']+SampleZ_min

df_sample.loc[(df_sample['C0']==1),'R_cenX'] = R_cen[0][0]
df_sample.loc[(df_sample['C0']==1),'R_cenY'] = R_cen[0][1]
df_sample.loc[(df_sample['C0']==2),'R_cenX'] = R_cen[1][0]
df_sample.loc[(df_sample['C0']==2),'R_cenY'] = R_cen[1][1]
df_sample.loc[(df_sample['C0']==3),'R_cenX'] = R_cen[2][0]
df_sample.loc[(df_sample['C0']==3),'R_cenY'] = R_cen[2][1]
df_sample.loc[(df_sample['C0']==4),'R_cenX'] = R_cen[3][0]
df_sample.loc[(df_sample['C0']==4),'R_cenY'] = R_cen[3][1]

#df_sample['X_cen']=math.sin(15/180*math.pi)*stick_width
#df_sample['X_min']=(df_sample['leftbot_horz']-stick_width/2)*math.sin(15/180*math.pi)+df_sample['X_cen']+df_sample['R_cenX']#-math.sin(15/180*math.pi)*stick_width+SampleX_min
#df_sample['X_max']=(df_sample['righttop_horz']-stick_width/2)*math.sin(15/180*math.pi)+df_sample['X_cen']+df_sample['R_cenX'] #-math.sin(15/180*math.pi)*stick_width+SampleX_min
df_sample['X_cen']=((df_sample['leftbot_hor']+df_sample['righttop_hor'])-stick_width)/2
df_sample['X_min']=df_sample['leftbot_hor']-stick_width/2
df_sample['X_max']=df_sample['righttop_hor']-stick_width/2
df_sample['Y_cen']=(df_sample['leftbot_dep']+df_sample['righttop_dep'])/2
df_sample['Z_cen']=(df_sample['leftbot_ver']+df_sample['righttop_ver'])/2+SampleZ_min
#df_sample['X_min']=(df_sample['leftbot_horz'])*math.sin(15/180*math.pi)-np.sqrt(2)*(stick_width/2-df_sample['X_cen']+df_sample['R_cenX']#-math.sin(15/180*math.pi)*stick_width+SampleX_min
#df_sample['X_max']=(df_sample['righttop_horz']-stick_width/2)*math.sin(15/180*math.pi)+df_sample['X_cen']+df_sample['R_cenX'] #-math.sin(15/180*math.pi)*stick_width+SampleX_min
#RR=15
#df_sample['X_cen15']=(df_sample['X_cen'])*math.sin(RR/180*math.pi)-np.sqrt(2)*(stick_width/2-df_sample['Y_cen'])*math.cos((90+45-RR)/180*math.pi)  +1*math.cos((90+45-RR)/180*math.pi) #df_sample['R_cenX']#+df_sample['R_cenX']#-math.sin(15/180*math.pi)*stick_width+SampleX_min
#df_sample['X_min15']=(df_sample['X_min'])*math.sin(RR/180*math.pi)-np.sqrt(2)*(stick_width/2-df_sample['Y_cen'])*math.cos((90+45-RR)/180*math.pi)  +1*math.cos((90+45-RR)/180*math.pi) #df_sample['R_cenX']#+df_sample['R_cenX']#-math.sin(15/180*math.pi)*stick_width+SampleX_min
#df_sample['X_max15']=(df_sample['X_max'])*math.sin(RR/180*math.pi)-np.sqrt(2)*(stick_width/2-df_sample['Y_cen'])*math.cos((90+45-RR)/180*math.pi)  +1*math.cos((90+45-RR)/180*math.pi) #df_sample['R_cenX']#+df_sample['R_cenX']#-math.sin(15/180*math.pi)*stick_width+SampleX_min

df_sample['E']=_experiment
outfile='./'+_experiment+'/pandas/df_sample.csv'
df_sample.to_csv(outfile)
#print(df_sample[['X_min15','X_cen15','X_max15','X_cen','Y_cen','Z_min','Z_cen','Z_max','R_min','R_max']])
print(df_sample[['ID','SAMPLE','Z_min','Z_cen','Z_max','R_min','R_max']])

def samplename_from_id(df_sample,id):
    samplename=df_sample[df_sample['ID']==id]["SAMPLE"]
    if len(samplename)!=0:
        return(samplename.tolist()[0])
    else:
        return(None)

     ID           SAMPLE  Z_min  Z_cen  Z_max  R_min  R_max
0   101           RTO2_1  460.5  463.0  465.5    0.1   90.1
1   102           RTO2_2  467.5  470.0  472.5    0.1   90.1
2   103           RTO2_3  475.5  478.0  480.5    0.1   90.1
3   104           RTO2_4  482.5  485.0  487.5    0.1   90.1
4   105           RTO2_5  490.5  493.0  495.5    0.1   90.1
5   106           RTO2_6  497.5  500.0  502.5    0.1   90.1
6   107  IrO2-TiO2_SL_08  505.5  508.0  510.5    0.1   90.1
7   108  IrO2-TiO2_SL_09  512.5  515.0  517.5    0.1   90.1
8   109  IrO2-TiO2_SL_10  519.5  522.0  524.5    0.1   90.1
9   201  IrO2-TiO2_SL_11  460.5  463.0  465.5   90.1  180.1
10  202  IrO2-TiO2_SL_12  468.5  471.0  473.5   90.1  180.1
11  203         IrO2_155  475.5  478.0  480.5   90.1  180.1
12  204         IrO2_168  482.5  485.0  487.5   90.1  180.1
13  205         IrO2_157  490.5  493.0  495.5   90.1  180.1
14  206         IrO2_159  498.5  501.0  503.5   90.1  180.1
15  207         IrO2_156  505.5  508.0  510.5   90.1  180.1
16  208         IrO2_169  512.5  515.0  517.5   90.1  180.1
17  209         RuO2_421  520.5  523.0  525.5   90.1  180.1
18  301         RuO2_201  460.5  463.0  465.5  180.1  270.1
19  302         RuO2_224  468.5  471.0  473.5  180.1  270.1
20  303         RuO2_356  475.5  478.0  480.5  180.1  270.1
21  304         RuO2_344  482.5  485.0  487.5  180.1  270.1

In [ ]:
samplename_from_id(df_sample,101)

'RTO2_1'

## Create sample scan paramerer DF

In [ ]:
#Obtain Epoch Timestamp on bl132lx
colnames=['Key','C0','C1','C2','C3','C4','C5',
          'C6','C7','C8','C9','C10',
          'C11','C12','C13','C14','C15',
          'C16','C17','C18','C19','C20']
colnames_sample=['Sample_C','C0','C1','SAMPLE','leftbot_hor','leftbot_dep','leftbot_ver','righttop_hor','righttop_dep','righttop_ver','C2','C3']

for _experiment in experiment:
    inputfile=home+_experiment+'/htxssample.csv'
    df_sample = pd.read_csv(inputfile, names=colnames_sample, header=None,sep=' ')
    df_sample['ID']=df_sample['C0']*100+df_sample['C1']
    df_sample['R_min']=((df_sample['C0'])%4*90-90+0.1)%360
    df_sample['R_max']=((df_sample['C0'])%4*90+0.1)%360

    df_sample.loc[(df_sample['C0']==1),'R_cenX'] = R_cen[0][0]
    df_sample.loc[(df_sample['C0']==1),'R_cenY'] = R_cen[0][1]
    df_sample.loc[(df_sample['C0']==2),'R_cenX'] = R_cen[1][0]
    df_sample.loc[(df_sample['C0']==2),'R_cenY'] = R_cen[1][1]
    df_sample.loc[(df_sample['C0']==3),'R_cenX'] = R_cen[2][0]
    df_sample.loc[(df_sample['C0']==3),'R_cenY'] = R_cen[2][1]
    df_sample.loc[(df_sample['C0']==4),'R_cenX'] = R_cen[3][0]
    df_sample.loc[(df_sample['C0']==4),'R_cenY'] = R_cen[3][1]
    df_sample.loc[(df_sample['C0']==1),'Z_min'] = R_cen[0][2]+df_sample['leftbot_ver']
    df_sample.loc[(df_sample['C0']==1),'Z_max'] = R_cen[0][2]+df_sample['righttop_ver']
    df_sample.loc[(df_sample['C0']==2),'Z_min'] = R_cen[1][2]+df_sample['leftbot_ver']
    df_sample.loc[(df_sample['C0']==2),'Z_max'] = R_cen[1][2]+df_sample['righttop_ver']
    df_sample.loc[(df_sample['C0']==3),'Z_min'] = R_cen[2][2]+df_sample['leftbot_ver']
    df_sample.loc[(df_sample['C0']==3),'Z_max'] = R_cen[2][2]+df_sample['righttop_ver']
    df_sample.loc[(df_sample['C0']==4),'Z_min'] = R_cen[3][2]+df_sample['leftbot_ver']
    df_sample.loc[(df_sample['C0']==4),'Z_max'] = R_cen[3][2]+df_sample['righttop_ver']


    df_sample['X_cen']=((df_sample['leftbot_hor']+df_sample['righttop_hor'])-stick_width)/2
    df_sample['X_min']=df_sample['leftbot_hor']-stick_width/2
    df_sample['X_max']=df_sample['righttop_hor']-stick_width/2
    df_sample['Y_cen']=(df_sample['leftbot_dep']+df_sample['righttop_dep'])/2

    df_sample.loc[(df_sample['C0']==1),'Z_cen'] = R_cen[0][2]+(df_sample['leftbot_ver']+df_sample['righttop_ver'])/2
    df_sample.loc[(df_sample['C0']==2),'Z_cen'] = R_cen[1][2]+(df_sample['leftbot_ver']+df_sample['righttop_ver'])/2
    df_sample.loc[(df_sample['C0']==3),'Z_cen'] = R_cen[2][2]+(df_sample['leftbot_ver']+df_sample['righttop_ver'])/2
    df_sample.loc[(df_sample['C0']==4),'Z_cen'] = R_cen[3][2]+(df_sample['leftbot_ver']+df_sample['righttop_ver'])/2

    #RR=15
    #df_sample['X_cen']=(df_sample['X_cen'])*math.sin(RR/180*math.pi)-np.sqrt(2)*(stick_width/2-df_sample['Y_cen'])*math.cos((90+45-RR)/180*math.pi)  +df_sample['R_cenX']*math.cos((90+45-RR)/180*math.pi) #df_sample['R_cenX']#+df_sample['R_cenX']#-math.sin(15/180*math.pi)*stick_width+SampleX_min
    #df_sample['X_min']=(df_sample['X_min'])*math.sin(RR/180*math.pi)-np.sqrt(2)*(stick_width/2-df_sample['Y_cen'])*math.cos((90+45-RR)/180*math.pi)  +df_sample['R_cenX']*math.cos((90+45-RR)/180*math.pi) #df_sample['R_cenX']#+df_sample['R_cenX']#-math.sin(15/180*math.pi)*stick_width+SampleX_min
    #df_sample['X_max']=(df_sample['X_max'])*math.sin(RR/180*math.pi)-np.sqrt(2)*(stick_width/2-df_sample['Y_cen'])*math.cos((90+45-RR)/180*math.pi)  +df_sample['R_cenX']*math.cos((90+45-RR)/180*math.pi) #df_sample['R_cenX']#+df_sample['R_cenX']#-math.sin(15/180*math.pi)*stick_width+SampleX_min


    df_sample['E']=_experiment
    outfile=dir+'/pandas/df_sample.pkl'
    df_sample.to_pickle(outfile)


    inputfile=dir+'/htxscom.csv'
    df_comments = pd.read_csv(inputfile, names=colnames, header=None,sep= ' ',na_filter=False)

    df_epoch0=df_comments[(df_comments['Key']=='#E')]['C0']
    df_epoch0_list=df_epoch0.to_list()
    df_epoch0index_list=df_epoch0.index.to_list()
    Epoch0=float(df_comments[(df_comments['Key']=='#E')]['C0'].values[0])-Epoch_offset

    df_sn=df_comments[(df_comments['Key']=='#S')]['C0'].reset_index().drop(columns=['index']).rename(columns={"C0": "S"})
    df_x=df_comments[(df_comments['Key']=='#P1')]['C6'].reset_index().drop(columns=['index']).rename(columns={"C6": "X"})
    df_y=df_comments[(df_comments['Key']=='#P1')]['C7'].reset_index().drop(columns=['index']).rename(columns={"C7": "Y"})
    df_z=df_comments[(df_comments['Key']=='#P2')]['C0'].reset_index().drop(columns=['index']).rename(columns={"C0": "Z"})
    df_r=df_comments[(df_comments['Key']=='#P2')]['C1'].reset_index().drop(columns=['index']).rename(columns={"C1": "R"})
    df_gap=df_comments[(df_comments['Key']=='#P0')]['C1'].reset_index().drop(columns=['index']).rename(columns={"C1": "GAP"})
    df_epu=df_comments[(df_comments['Key']=='#P0')]['C0'].reset_index().drop(columns=['index']).rename(columns={"C0": "EPU"})
    df_sgmensw=df_comments[(df_comments['Key']=='#P0')]['C5'].reset_index().drop(columns=['index']).rename(columns={"C5": "SGMENSW"})
    df_sgmensz=df_comments[(df_comments['Key']=='#P0')]['C4'].reset_index().drop(columns=['index']).rename(columns={"C4": "SGMENSZ"})
    df_m1pit=df_comments[(df_comments['Key']=='#P0')]['C3'].reset_index().drop(columns=['index']).rename(columns={"C3": "M1PIT"})
    df_m0pit=df_comments[(df_comments['Key']=='#P0')]['C2'].reset_index().drop(columns=['index']).rename(columns={"C2": "M0PIT"})
    df_exsv_2=df_comments[(df_comments['Key']=='#P1')]['C0'].reset_index().drop(columns=['index']).rename(columns={"C0": "EXSV_2"})
    df_sgmhorz=df_comments[(df_comments['Key']=='#P0')]['C6'].reset_index().drop(columns=['index']).rename(columns={"C6": "SGMHORZ"})
    df_mono132=df_comments[(df_comments['Key']=='#P1')]['C1'].reset_index().drop(columns=['index']).rename(columns={"C1": "MONO132"})

    droplist=df_comments.loc[(df_comments['Key']=='#E')].index.to_list()
    i=0
    for y in droplist:
        droplist[i]=y+1
        i=i+1
    df_comments['EPOCH0']=df_epoch0_list[0]
    kk=0
    for k in df_epoch0index_list:
        df_comments.loc[(df_comments.index>=k),'EPOCH0'] = df_epoch0_list[kk]
        kk=kk+1

    df_datetime=df_comments.loc[(df_comments['Key']=='#D')][["C4","C1","C2","C3","EPOCH0"]].drop(index=droplist).reset_index().drop(columns=['index'])

    df_datetime['DATETIME'] = df_datetime.agg(lambda x: f"{x['C4']} {x['C1']} {x['C2']} {x['C3']}", axis=1)

    df_datetime['EPOCH']=''
    for index, row in df_datetime.iterrows():
        row['EPOCH'] = datetime.datetime.timestamp(datetime.datetime.strptime(row['DATETIME'],"%Y %b %d %H:%M:%S"))-Epoch_offset
    df_datetime['EPOCH']=row['EPOCH']
    df_epoch=df_datetime['EPOCH'].reset_index().drop(columns=['index'])
    df_epoch0=df_datetime['EPOCH0'].reset_index()#.drop(columns=['index'])


    df_scan =df_comments[df_comments['Key']=='#S'].reset_index().drop(columns=['index'])   # key to extract fascan

    df_scan['colnames']=''
    df_scan['scan']=''
    colnames0="'"+df_scan["C2"]+"'"
    colnames1="'mono132','gap'"
    colnames2="'time'"
    df_scan.loc[((df_scan['C1']=='gscan') | (df_scan['C1']=='ascan')),'colnames']=colnames0
    df_scan.loc[((df_scan['C1']=='tes_local_gscan') | (df_scan['C1']=='ascan')),'colnames']=colnames0
    df_scan.loc[(df_scan['C1']=='fscan'),'colnames']=colnames1
    df_scan.loc[(df_scan['C1']=='timescan')| (df_scan['C1']=='loopscan'),'colnames']=colnames2

    scancmd_list=[]
    for index, row in df_scan.iterrows():
        scancmd=f"{row['C1']} {row['C2']} {row['C3']} {row['C4']} {row['C5']} {row['C6']} {row['C7']} {row['C8']} {row['C9']} {row['C10']} {row['C11']} {row['C12']}"

        scancmd_list.append(scancmd.strip())


    df_scancmd=pd.DataFrame(scancmd_list, columns=['scancmd'])
    colname_list=df_scan['colnames'].tolist()
    df_colnames=pd.DataFrame(colname_list, columns=['C'])

    df_xyzr= pd.concat([df_sn,df_x,df_y,df_z,df_r,df_mono132,df_gap,df_epu,df_m0pit,df_m1pit,df_sgmensw,df_sgmensz,df_sgmhorz,df_exsv_2,df_epoch,df_scancmd,df_colnames,df_epoch0], axis=1)

    samplename_list=[]
    sampleid_list=[]
    scanstring_list=[]
    angle_list=[]
    for index, row in df_xyzr.iterrows():
        X0=round(float(row['X']),2)
        Y0=round(float(row['Y']),2)
        Z0=round(float(row['Z']),2)
        R0=round(float(row['R']),2)
        M0=round(float(row['MONO132']),2)

        samplename=samplename_from_xyzr(df_sample,X0,Y0,Z0,R0)
        sampleid=sampleid_from_xyzr(df_sample,X0,Y0,Z0,R0)
        samplename_list.append(samplename)
        angle_list.append(round(R0%90,1))

        sampleid_list.append(sampleid)

        scanstring_list.append(scanstring_from_mono132(M0))

    df_angle=pd.DataFrame(angle_list, columns=['angle']).reset_index().drop(columns=['index'])
    df_samplename=pd.DataFrame(samplename_list, columns=['samplename']).reset_index().drop(columns=['index'])
    df_sampleid=pd.DataFrame(sampleid_list, columns=['sampleid']).reset_index().drop(columns=['index'])
    df_scanstring=pd.DataFrame(scanstring_list, columns=['XAS']).reset_index().drop(columns=['index'])
    df_angle=pd.DataFrame(angle_list, columns=['angle']).reset_index().drop(columns=['index'])
    df_xyzr= pd.concat([df_samplename,df_sampleid,df_angle,df_scanstring,df_sn,df_x,df_y,df_z,df_r,df_mono132,df_gap,df_epu,df_m0pit,df_m1pit,df_sgmensw,df_sgmensz,df_sgmhorz,df_exsv_2,df_epoch,df_epoch0,df_scancmd,df_colnames], axis=1)

    #df_xyzr['S']=df_xyzr['S'].astype(int)
    df_xyzr['E']=_experiment
    df_xyzr['F']=df_xyzr.index+1
    #df_xyzr['angle']=round(df_xyzr['R']%90,0)
    #print(df_xyzr)
    outfile=home+_experiment+'/pandas/df_xyzr.csv'
    df_xyzr.to_csv(outfile)
#SGMENSW, EXSV_2, SGMHORZ, GAP, EPU,

In [ ]:
df_xyzr

,samplename,sampleid,angle,XAS,S,X,Y,Z,R,MONO132,...,SGMENSZ,SGMHORZ,EXSV_2,EPOCH,index,EPOCH0,scancmd,C,E,F
0,None,NaN,0.0,Ti,1,-6,0,460,90.000987,464,...,100,99.05,1.75,1.734345e+09,0,1734208915,ascan m1pit -422.4 -302.4 40 1,'m1pit',20241214,1
1,IrO2-TiO2_SL_10,109.0,0.0,Ti,2,-5,-10.525,520.2,90.000987,470.0009,...,100,99.05,1.75,1.734345e+09,1,1734208915,ascan samplez 525 455 140 0.5,'samplez',20241214,2
2,photodiode,NaN,0.0,Ti,3,-5,-10.525,455,90.000987,470.0009,...,100,99.05,1.75,1.734345e+09,2,1734208915,timescan 1 0,'time',20241214,3
3,RTO2_1,101.0,0.0,Ti,4,-5.0735,-10.525,461.2,90.000987,470.0009,...,100,99.05,1.75,1.734345e+09,3,1734208915,ascan samplex -2 3 50 0.5,'samplex',20241214,4
4,RTO2_1,101.0,0.0,Ti,5,-1.122,-10.525,461.2,90.000987,470.0009,...,100,99.05,1.75,1.734345e+09,4,1734208915,ascan samplex -2 -8 50 0.5,'samplex',20241214,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
825,RuO2_356,303.0,30.0,O,826,5.69,-8.7485,476.7,209.9973,546.0008,...,100,99.05,1.8,1.734345e+09,825,1734288855,gscan mono132 524 526 0.2 535 0.1 546 0.2 1.7,'mono132',20241214,826
826,RuO2_356,303.0,30.0,O,827,5.69,-8.7485,476.7,209.9973,546.0008,...,100,99.05,1.8,1.734345e+09,826,1734288855,gscan mono132 524 526 0.2 535 0.1 546 0.2 1.7,'mono132',20241214,827
827,RuO2_344,304.0,30.0,O,828,5.7175,-8.7485,483.7,209.9973,546.0008,...,100,99.05,1.8,1.734345e+09,827,1734288855,gscan mono132 524 526 0.2 535 0.1 546 0.2 1.7,'mono132',20241214,828
828,RuO2_344,304.0,30.0,O,829,5.7175,-8.7485,483.7,209.9973,546.0008,...,100,99.05,1.8,1.734345e+09,828,1734288855,gscan mono132 524 526 0.2 535 0.1 546 0.2 1.7,'mono132',20241214,829
829,photodiode,NaN,0.0,O,830,-10,17,5,-2.6834531e-07,546.0008,...,100,99.05,1.8,1.734345e+09,829,1734288855,timescan 1 0,'time',20241214,830

# Reload DF

In [ ]:
inputfile=home+_experiment+'/pandas/df_xyzr.csv'
DF_XYZR=pd.read_csv(inputfile)
DF_XYZR.sampleid=DF_XYZR.sampleid.fillna(-1).astype(int)
inputfile=home+_experiment+'/pandas/df_sample.csv'
DF_SAMPLE=pd.read_csv(inputfile)

# Export DF

# Check Dataframe files

In [ ]:
DF_XYZR

,Unnamed: 0,samplename,sampleid,XAS,S,X,Y,Z,R,MONO132,...,SGMENSZ,SGMHORZ,EXSV_2,EPOCH,index,EPOCH0,scancmd,C,E,F
0,0,not_found,NaN,Ti,1,-6.0000,0.000,460.0000,90.000987,464.0000,...,100,99.05,1.75,1.734261e+09,0,1734208915,ascan m1pit -422.4 -302.4 40 1,'m1pit',20241214,1
1,1,not_found,NaN,Ti,2,-5.0000,-10.525,520.2000,90.000987,470.0009,...,100,99.05,1.75,1.734261e+09,1,1734208915,ascan samplez 525 455 140 0.5,'samplez',20241214,2
2,2,photodiode,NaN,Ti,3,-5.0000,-10.525,455.0000,90.000987,470.0009,...,100,99.05,1.75,1.734261e+09,2,1734208915,timescan 1 0,'time',20241214,3
3,3,not_found,NaN,Ti,4,-5.0735,-10.525,461.2000,90.000987,470.0009,...,100,99.05,1.75,1.734261e+09,3,1734208915,ascan samplex -2 3 50 0.5,'samplex',20241214,4
4,4,not_found,NaN,Ti,5,-1.1220,-10.525,461.2000,90.000987,470.0009,...,100,99.05,1.75,1.734261e+09,4,1734208915,ascan samplex -2 -8 50 0.5,'samplex',20241214,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,179,RuO2_201,301.0,O,180,1.7110,-10.650,461.2000,230.001690,527.7515,...,100,99.05,1.80,1.734261e+09,179,1734288855,gscan mono132 520 528 0.25 538 0.1 550 0.2 1.8,'mono132',20241214,180
180,180,RuO2_201,301.0,O,181,1.7110,-10.650,461.2000,230.001690,523.7509,...,100,99.05,1.80,1.734261e+09,180,1734288855,ascan m1pit -467.6 -347.6 40 1,'m1pit',20241214,181
181,181,RTO2_6,106.0,O,182,-1.8715,-11.267,502.1835,69.996600,520.0002,...,100,99.05,1.80,1.734261e+09,181,1734288855,ascan mono132 534 530 10 0.5,'mono132',20241214,182
182,182,RTO2_6,106.0,O,183,-1.8715,-11.267,502.1835,69.996600,531.9998,...,100,99.05,1.80,1.734261e+09,182,1734288855,gscan mono132 524 526 0.2 535 0.1 546 0.2 1.7,'mono132',20241214,183
183,183,RTO2_1,101.0,O,184,-2.6310,-11.267,462.2000,69.996600,520.0000,...,100,99.05,1.80,1.734261e+09,183,1734288855,gscan mono132 524 526 0.2 535 0.1 546 0.2 1.7,'mono132',20241214,184

In [ ]:
DF_SAMPLE

,Unnamed: 0,Sample_C,C0,C1,name,leftbot_hor,leftbot_dep,leftbot_ver,righttop_hor,righttop_dep,...,R_cenY,X_cen,X_min,X_max,Y_cen,Z_cen,X_cen15,X_min15,X_max15,E
0,0,htxs_set_sample_info,1,1,RTO2_1,4,-1,5,9,-1,...,0.0,-3.025,-5.525,-0.525,-1.0,463.0,6.159371,5.512324,6.806419,20241214
1,1,htxs_set_sample_info,1,2,RTO2_2,4,-1,12,9,-1,...,0.0,-3.025,-5.525,-0.525,-1.0,470.0,6.159371,5.512324,6.806419,20241214
2,2,htxs_set_sample_info,1,3,RTO2_3,4,-1,20,9,-1,...,0.0,-3.025,-5.525,-0.525,-1.0,478.0,6.159371,5.512324,6.806419,20241214
3,3,htxs_set_sample_info,1,4,RTO2_4,4,-1,27,9,-1,...,0.0,-3.025,-5.525,-0.525,-1.0,485.0,6.159371,5.512324,6.806419,20241214
4,4,htxs_set_sample_info,1,5,RTO2_5,4,-1,35,9,-1,...,0.0,-3.025,-5.525,-0.525,-1.0,493.0,6.159371,5.512324,6.806419,20241214
5,5,htxs_set_sample_info,1,6,RTO2_6,4,-1,42,9,-1,...,0.0,-3.025,-5.525,-0.525,-1.0,500.0,6.159371,5.512324,6.806419,20241214
6,6,htxs_set_sample_info,1,7,IrO2-TiO2_SL_08,4,-1,50,9,-1,...,0.0,-3.025,-5.525,-0.525,-1.0,508.0,6.159371,5.512324,6.806419,20241214
7,7,htxs_set_sample_info,1,8,IrO2-TiO2_SL_09,4,-1,57,9,-1,...,0.0,-3.025,-5.525,-0.525,-1.0,515.0,6.159371,5.512324,6.806419,20241214
8,8,htxs_set_sample_info,1,9,IrO2-TiO2_SL_10,4,-1,64,9,-1,...,0.0,-3.025,-5.525,-0.525,-1.0,522.0,6.159371,5.512324,6.806419,20241214
9,9,htxs_set_sample_info,2,1,IrO2-TiO2_SL_11,4,-1,5,9,-1,...,0.0,-3.025,-5.525,-0.525,-1.0,463.0,6.159371,5.512324,6.806419,20241214
10,10,htxs_set_sample_info,2,2,IrO2-TiO2_SL_12,4,-1,13,9,-1,...,0.0,-3.025,-5.525,-0.525,-1.0,471.0,6.159371,5.512324,6.806419,20241214
11,11,htxs_set_sample_info,2,3,IrO2_155,4,-1,20,9,-1,...,0.0,-3.025,-5.525,-0.525,-1.0,478.0,6.159371,5.512324,6.806419,20241214
12,12,htxs_set_sample_info,2,4,IrO2_168,4,-1,27,9,-1,...,0.0,-3.025,-5.525,-0.525,-1.0,485.0,6.159371,5.512324,6.806419,20241214
13,13,htxs_set_sample_info,2,5,IrO2_157,4,-1,35,9,-1,...,0.0,-3.025,-5.525,-0.525,-1.0,493.0,6.159371,5.512324,6.806419,20241214
14,14,htxs_set_sample_info,2,6,IrO2_159,4,-1,43,9,-1,...,0.0,-3.025,-5.525,-0.525,-1.0,501.0,6.159371,5.512324,6.806419,20241214
15,15,htxs_set_sample_info,2,7,IrO2_156,4,-1,50,9,-1,...,0.0,-3.025,-5.525,-0.525,-1.0,508.0,6.159371,5.512324,6.806419,20241214
16,16,htxs_set_sample_info,2,8,IrO2_169,4,-1,57,9,-1,...,0.0,-3.025,-5.525,-0.525,-1.0,515.0,6.159371,5.512324,6.806419,20241214
17,17,htxs_set_sample_info,2,9,RuO2_421,4,-1,65,9,-1,...,0.0,-3.025,-5.525,-0.525,-1.0,523.0,6.159371,5.512324,6.806419,20241214
18,18,htxs_set_sample_info,3,1,RuO2_201,4,-1,5,9,-1,...,0.0,-3.025,-5.525,-0.525,-1.0,463.0,6.159371,5.512324,6.806419,20241214
19,19,htxs_set_sample_info,3,2,RuO2_224,4,-1,13,9,-1,...,0.0,-3.025,-5.525,-0.525,-1.0,471.0,6.159371,5.512324,6.806419,20241214
20,20,htxs_set_sample_info,3,3,RuO2_356,4,-1,20,9,-1,...,0.0,-3.025,-5.525,-0.525,-1.0,478.0,6.159371,5.512324,6.806419,20241214
21,21,htxs_set_sample_info,3,4,RuO2_344,4,-1,27,9,-1,...,0.0,-3.025,-5.525,-0.525,-1.0,485.0,6.159371,5.512324,6.806419,20241214

# XAS

## make XAS file list

In [ ]:
load_list=[]
for _experiment in experiment:
    pathstr=home+_experiment+'/spec/'
    for x in os.listdir(pathstr):
        if x.startswith("htxs_scan") & x.endswith(".csv"):
          load_list.append([_experiment,int(x.strip('htxs_scan.csv')),x.strip('htxs_scan.csv')])
load_list.sort()

In [ ]:
load_list

In [ ]:
recent_df=[]
recent_df_str=[]

for k in load_list:
    j=str(k[2])
    l=k[0]
    m=k[2]

    colnames="["+DF_XYZR[(DF_XYZR['F']==int(j))&(DF_XYZR['E']==l)]['C'].to_string(index=False)+colnames_base
    colnameslist = ["line","mono132",  "Seconds", "I0", "SC","ZOM", "CH","FY","REF", "I1", "testfy", "CTEMP"]
    df_str="xas_"+m+"_"+str(j)

    prog=df_str+" =pd.read_csv("+'"'+home+l+"/spec/htxs_scan" + str(j)+'.csv"'+",comment='#',names=colnameslist,sep=',',"+"skiprows=1"+")"
    exec(prog, globals(), locals())

    cmd_str="xas_"+m+"_"+str(j)+".insert(0,'dataframe','xas_"+str(j)+"')"
    exec(cmd_str)
    cmd_str="xas_"+m+"_"+str(j)+".insert(1,'D',"+str(j)+")"  #file ID
    exec(cmd_str)
    sample_name=DF_XYZR.loc[(DF_XYZR['F']==int(j))&(DF_XYZR['E']==int(l))]["samplename"].tolist()[0]
    cmd_str="xas_"+m+"_"+str(j)+".insert(2,'SAMPLE',sample_name)"
    exec(cmd_str)
    sample_x=DF_XYZR.loc[(DF_XYZR['F']==int(j))&(DF_XYZR['E']==int(l))]["X"].tolist()[0]
    cmd_str="xas_"+m+"_"+str(j)+".insert(2,'X',sample_x)"
    exec(cmd_str)
    sample_y=DF_XYZR.loc[(DF_XYZR['F']==int(j))&(DF_XYZR['E']==int(l))]["Y"].tolist()[0]
    cmd_str="xas_"+m+"_"+str(j)+".insert(2,'Y',sample_y)"
    exec(cmd_str)
    sample_z=DF_XYZR.loc[(DF_XYZR['F']==int(j))&(DF_XYZR['E']==int(l))]["Z"].tolist()[0]
    cmd_str="xas_"+m+"_"+str(j)+".insert(2,'Z',sample_z)"
    exec(cmd_str)
    sample_r=DF_XYZR.loc[(DF_XYZR['F']==int(j))&(DF_XYZR['E']==int(l))]["R"].tolist()[0]
    cmd_str="xas_"+m+"_"+str(j)+".insert(2,'R',sample_r)"
    exec(cmd_str)
    sample_id=DF_XYZR.loc[(DF_XYZR['F']==int(j))&(DF_XYZR['E']==int(l))]["sampleid"].tolist()[0]
    cmd_str="xas_"+m+"_"+str(j)+".insert(2,'ID',sample_id)"
    exec(cmd_str)
    experiment_n=DF_XYZR.loc[(DF_XYZR['F']==int(j))&(DF_XYZR['E']==int(l))]["E"].tolist()[0]
    cmd_str="xas_"+m+"_"+str(j)+".insert(2,'E',experiment_n)"
    exec(cmd_str)
    scan_n=DF_XYZR.loc[(DF_XYZR['F']==int(j))&(DF_XYZR['E']==int(l))]["S"].tolist()[0]
    cmd_str="xas_"+m+"_"+str(j)+".insert(2,'S',scan_n)"
    exec(cmd_str)
    motor_n=DF_XYZR.loc[(DF_XYZR['F']==int(j))&(DF_XYZR['E']==int(l))]["C"].tolist()[0]
    cmd_str="xas_"+m+"_"+str(j)+".insert(2,'C',motor_n)"
    exec(cmd_str)
    file_n=DF_XYZR.loc[(DF_XYZR['F']==int(j))&(DF_XYZR['E']==int(l))]["F"].tolist()[0]
    cmd_str="xas_"+m+"_"+str(j)+".insert(2,'F',file_n)"
    exec(cmd_str)
    gap_v=DF_XYZR.loc[(DF_XYZR['F']==int(j))&(DF_XYZR['E']==int(l))]["GAP"].tolist()[0]
    cmd_str="xas_"+m+"_"+str(j)+".insert(2,'GAP',gap_v)"
    exec(cmd_str)
    epu_v=DF_XYZR.loc[(DF_XYZR['F']==int(j))&(DF_XYZR['E']==int(l))]["EPU"].tolist()[0]
    cmd_str="xas_"+m+"_"+str(j)+".insert(2,'EPU',epu_v)"
    exec(cmd_str)
    sgmensw_v=DF_XYZR.loc[(DF_XYZR['F']==int(j))&(DF_XYZR['E']==int(l))]["SGMENSW"].tolist()[0]
    cmd_str="xas_"+m+"_"+str(j)+".insert(2,'SGMENSW',sgmensw_v)"
    exec(cmd_str)
    sgmensz_v=DF_XYZR.loc[(DF_XYZR['F']==int(j))&(DF_XYZR['E']==int(l))]["SGMENSZ"].tolist()[0]
    cmd_str="xas_"+m+"_"+str(j)+".insert(2,'SGMENSZ',sgmensz_v)"
    exec(cmd_str)
    m1pit_v=DF_XYZR.loc[(DF_XYZR['F']==int(j))&(DF_XYZR['E']==int(l))]["M1PIT"].tolist()[0]
    cmd_str="xas_"+m+"_"+str(j)+".insert(2,'M1PIT',m1pit_v)"
    exec(cmd_str)
    m0pit_v=DF_XYZR.loc[(DF_XYZR['F']==int(j))&(DF_XYZR['E']==int(l))]["M0PIT"].tolist()[0]
    cmd_str="xas_"+m+"_"+str(j)+".insert(2,'M0PIT',m0pit_v)"
    exec(cmd_str)
    exsv2_v=DF_XYZR.loc[(DF_XYZR['F']==int(j))&(DF_XYZR['E']==int(l))]["EXSV_2"].tolist()[0]
    cmd_str="xas_"+m+"_"+str(j)+".insert(2,'EXSV_2',exsv2_v)"
    exec(cmd_str)
    sgmhorz_v=DF_XYZR.loc[(DF_XYZR['F']==int(j))&(DF_XYZR['E']==int(l))]["SGMHORZ"].tolist()[0]
    cmd_str="xas_"+m+"_"+str(j)+".insert(2,'SGMHORZ',sgmhorz_v)"
    exec(cmd_str)
    mono132_v=DF_XYZR.loc[(DF_XYZR['F']==int(j))&(DF_XYZR['E']==int(l))]["MONO132"].tolist()[0]
    cmd_str="xas_"+m+"_"+str(j)+".insert(2,'MONO132',mono132_v)"
    exec(cmd_str)
    epoch_v=DF_XYZR.loc[(DF_XYZR['F']==int(j))&(DF_XYZR['E']==int(l))]["EPOCH"].tolist()[0]
    cmd_str="xas_"+m+"_"+str(j)+".insert(2,'EPOCH',epoch_v)"
    exec(cmd_str)
    scan_v=DF_XYZR.loc[(DF_XYZR['F']==int(j))&(DF_XYZR['E']==int(l))]["scancmd"].tolist()[0]
    cmd_str="xas_"+m+"_"+str(j)+".insert(2,'SCAN',scan_v)"
    exec(cmd_str)

    df_xyzr.loc[((DF_XYZR['F']==int(j))&(DF_XYZR['E']==int(l))),'dataframe']=df_str#"xas_"+str(j)

    x=globals()[df_str]

    cmd_str=""
    scanstring_list=[]

    recent_df_str.append(df_str)
    recent_df.append(globals()[df_str])

    print(k[0],k[2],end='\n')

#SAVE
DF_XAS=pd.concat(recent_df,ignore_index=False,axis=0)
for _experiment in experiment:
#df_xas=DF_XAS[DF_XAS.E==_experiment]
    outfile=home+_experiment+'/pandas/df_xas.csv'
    DF_XAS[DF_XAS.E==_experiment].to_csv(outfile)

20241214 1
20241214 2
20241214 3
20241214 4
20241214 5
20241214 6
20241214 7
20241214 8
20241214 9
20241214 10
20241214 11
20241214 12
20241214 13
20241214 14
20241214 15
20241214 16
20241214 17
20241214 18
20241214 19
20241214 20
20241214 21
20241214 22
20241214 23
20241214 24
20241214 25
20241214 26
20241214 27
20241214 28
20241214 29
20241214 30
20241214 31
20241214 32
20241214 33
20241214 34
20241214 35
20241214 36
20241214 37
20241214 38
20241214 39
20241214 40
20241214 41
20241214 42
20241214 43
20241214 44
20241214 45
20241214 46
20241214 47
20241214 48
20241214 49
20241214 50
20241214 51
20241214 52
20241214 53
20241214 54
20241214 55
20241214 56
20241214 57
20241214 58
20241214 59
20241214 60
20241214 61
20241214 62
20241214 63
20241214 64
20241214 65
20241214 66
20241214 67
20241214 68
20241214 69
20241214 70
20241214 71
20241214 72
20241214 73
20241214 74
20241214 75
20241214 76
20241214 77
20241214 78
20241214 79
20241214 80
20241214 81
20241214 82
20241214 83
20241214 84
20241214 85
20241214 86
20241214 87
20241214 88
20241214 89
20241214 90
20241214 91
20241214 92
20241214 93
20241214 94
20241214 95
20241214 96
20241214 97
20241214 98
20241214 99
20241214 100
20241214 101
20241214 102
20241214 103
20241214 104
20241214 105
20241214 106
20241214 107
20241214 108
20241214 109
20241214 110
20241214 111
20241214 112
20241214 113
20241214 114
20241214 115
20241214 116
20241214 117
20241214 118
20241214 119
20241214 120
20241214 121
20241214 122
20241214 123
20241214 124
20241214 125
20241214 126
20241214 127
20241214 128
20241214 129
20241214 130
20241214 131
20241214 132
20241214 133
20241214 134
20241214 135
20241214 136
20241214 137
20241214 138
20241214 139
20241214 140
20241214 141
20241214 142
20241214 143
20241214 144
20241214 145
20241214 146
20241214 147
20241214 148
20241214 149
20241214 150
20241214 151
20241214 152
20241214 153
20241214 154
20241214 155
20241214 156
20241214 157
20241214 158
20241214 159
20241214 160
20241214 161
20241214 162
20241214 163
20241214 164
20241214 165
20241214 166
20241214 167
20241214 168
20241214 169
20241214 170
20241214 171
20241214 172
20241214 173
20241214 174
20241214 175
20241214 176
20241214 177
20241214 178
20241214 179
20241214 180
20241214 181
20241214 182
20241214 183
20241214 184
20241214 185
20241214 186
20241214 187
20241214 188
20241214 189
20241214 190
20241214 191
20241214 192
20241214 193
20241214 194
20241214 195
20241214 196
20241214 197
20241214 198
20241214 199
20241214 200
20241214 201
20241214 202
20241214 203
20241214 204
20241214 205
20241214 206
20241214 207
20241214 208
20241214 209
20241214 210
20241214 211
20241214 212
20241214 213
20241214 214
20241214 215
20241214 216
20241214 217
20241214 218
20241214 219
20241214 220
20241214 221
20241214 222
20241214 223
20241214 224
20241214 225
20241214 226
20241214 227
20241214 228
20241214 229
20241214 230
20241214 231
20241214 232
20241214 233
20241214 234
20241214 235
20241214 236
20241214 237
20241214 238
20241214 239
20241214 240
20241214 241
20241214 242
20241214 243
20241214 244
20241214 245
20241214 246
20241214 247
20241214 248
20241214 249
20241214 250
20241214 251
20241214 252
20241214 253
20241214 254
20241214 255
20241214 256
20241214 257
20241214 258
20241214 259
20241214 260
20241214 261
20241214 262
20241214 263
20241214 264
20241214 265
20241214 266
20241214 267
20241214 268
20241214 269
20241214 270
20241214 271
20241214 272
20241214 273
20241214 274
20241214 275
20241214 276
20241214 277
20241214 278
20241214 279
20241214 280
20241214 281
20241214 282
20241214 283
20241214 284
20241214 285
20241214 286
20241214 287
20241214 288
20241214 289
20241214 290
20241214 291
20241214 292
20241214 293
20241214 294
20241214 295
20241214 296
20241214 297
20241214 298
20241214 299
20241214 300
20241214 301
20241214 302
20241214 303
20241214 304
20241214 305
20241214 306
20241214 307
20241214 308
20241214 309
20241214 310
20241214 311
20241214 312
20241214 313
20241214 314
20241214 315
20241214 316
20241214 317
20241214 318
20241214 319
20241214 320
20241214 321
20241214 322
20241214 323
20241214 324
20241214 325
20241214 326
20241214 327
20241214 328
20241214 329
20241214 330
20241214 331
20241214 332
20241214 333
20241214 334
20241214 335
20241214 336
20241214 337
20241214 338
20241214 339
20241214 340
20241214 341
20241214 342
20241214 343
20241214 344
20241214 345
20241214 346
20241214 347
20241214 348
20241214 349
20241214 350
20241214 351
20241214 352
20241214 353
20241214 354
20241214 355
20241214 356
20241214 357
20241214 358
20241214 359
20241214 360
20241214 361
20241214 362
20241214 363
20241214 364
20241214 365
20241214 366
20241214 367
20241214 368
20241214 369
20241214 370
20241214 371
20241214 372
20241214 373
20241214 374
20241214 375
20241214 376
20241214 377
20241214 378
20241214 379
20241214 380
20241214 381
20241214 382
20241214 383
20241214 384
20241214 385
20241214 386
20241214 387
20241214 388
20241214 389
20241214 390
20241214 391
20241214 392
20241214 393
20241214 394
20241214 395
20241214 396
20241214 397
20241214 398
20241214 399
20241214 400
20241214 401
20241214 402
20241214 403
20241214 404
20241214 405
20241214 406
20241214 407
20241214 408
20241214 409
20241214 410
20241214 411
20241214 412
20241214 413
20241214 414
20241214 415
20241214 416
20241214 417
20241214 418
20241214 419
20241214 420
20241214 421
20241214 422
20241214 423
20241214 424
20241214 425
20241214 426
20241214 427
20241214 428
20241214 429
20241214 430
20241214 431
20241214 432
20241214 433
20241214 434
20241214 435
20241214 436
20241214 437
20241214 438
20241214 439
20241214 440
20241214 441
20241214 442
20241214 443
20241214 444
20241214 445
20241214 446
20241214 447
20241214 448
20241214 449
20241214 450
20241214 451
20241214 452
20241214 453
20241214 454
20241214 455
20241214 456
20241214 457
20241214 458
20241214 459
20241214 460
20241214 461
20241214 462
20241214 463
20241214 464
20241214 465
20241214 466
20241214 467
20241214 468
20241214 469
20241214 470
20241214 471
20241214 472
20241214 473
20241214 474
20241214 475
20241214 476
20241214 477
20241214 478
20241214 479
20241214 480
20241214 481
20241214 482
20241214 483
20241214 484
20241214 485
20241214 486
20241214 487
20241214 488
20241214 489
20241214 490
20241214 491
20241214 492
20241214 493
20241214 494
20241214 495
20241214 496
20241214 497
20241214 498
20241214 499
20241214 500
20241214 501
20241214 502
20241214 503
20241214 504
20241214 505
20241214 506
20241214 507
20241214 508
20241214 509
20241214 510
20241214 511
20241214 512
20241214 513
20241214 514
20241214 515
20241214 516
20241214 517
20241214 518
20241214 519
20241214 520
20241214 521
20241214 522
20241214 523
20241214 524
20241214 525
20241214 526
20241214 527
20241214 528
20241214 529
20241214 530
20241214 531
20241214 532
20241214 533
20241214 534
20241214 535
20241214 536
20241214 537
20241214 538
20241214 539
20241214 540
20241214 541
20241214 542
20241214 543
20241214 544
20241214 545
20241214 546
20241214 547
20241214 548
20241214 549
20241214 550
20241214 551
20241214 552
20241214 553
20241214 554
20241214 555
20241214 556
20241214 557
20241214 558
20241214 559
20241214 560
20241214 561
20241214 562
20241214 563
20241214 564
20241214 565
20241214 566
20241214 567
20241214 568
20241214 569
20241214 570
20241214 571
20241214 572
20241214 573
20241214 574
20241214 575
20241214 576
20241214 577
20241214 578
20241214 579
20241214 580
20241214 581
20241214 582
20241214 583
20241214 584
20241214 585
20241214 586
20241214 587
20241214 588
20241214 589
20241214 590
20241214 591
20241214 592
20241214 593
20241214 594
20241214 595
20241214 596
20241214 597
20241214 598
20241214 599
20241214 600
20241214 601
20241214 602
20241214 603
20241214 604
20241214 605
20241214 606
20241214 607
20241214 608
20241214 609
20241214 610
20241214 611
20241214 612
20241214 613
20241214 614
20241214 615
20241214 616
20241214 617
20241214 618
20241214 619
20241214 620
20241214 621
20241214 622
20241214 623
20241214 624
20241214 625
20241214 626
20241214 627
20241214 628
20241214 629
20241214 630
20241214 631
20241214 632
20241214 633
20241214 634
20241214 635
20241214 636
20241214 637
20241214 638
20241214 639
20241214 640
20241214 641
20241214 642
20241214 643
20241214 644
20241214 645
20241214 646
20241214 647
20241214 648
20241214 649
20241214 650
20241214 651
20241214 652
20241214 653
20241214 654
20241214 655
20241214 656
20241214 657
20241214 658
20241214 659
20241214 660
20241214 661
20241214 662
20241214 663
20241214 664
20241214 665
20241214 666
20241214 667
20241214 668
20241214 669
20241214 670
20241214 671
20241214 672
20241214 673
20241214 674
20241214 675
20241214 676
20241214 677
20241214 678
20241214 679
20241214 680
20241214 681
20241214 682
20241214 683
20241214 684
20241214 685
20241214 686
20241214 687
20241214 688
20241214 689
20241214 690
20241214 691
20241214 692
20241214 693
20241214 694
20241214 695
20241214 696
20241214 697
20241214 698
20241214 699
20241214 700
20241214 701
20241214 702
20241214 703
20241214 704
20241214 705
20241214 706
20241214 707
20241214 708
20241214 709
20241214 710
20241214 711
20241214 712
20241214 713
20241214 714
20241214 715
20241214 716
20241214 717
20241214 718
20241214 719
20241214 720
20241214 721
20241214 722
20241214 723
20241214 724
20241214 725
20241214 726
20241214 727
20241214 728
20241214 729
20241214 730
20241214 731
20241214 732
20241214 733
20241214 734
20241214 735
20241214 736
20241214 737
20241214 738
20241214 739
20241214 740
20241214 741
20241214 742
20241214 743
20241214 744
20241214 745
20241214 746
20241214 747
20241214 748
20241214 749
20241214 750
20241214 751
20241214 752
20241214 753
20241214 754
20241214 755
20241214 756
20241214 757
20241214 758
20241214 759
20241214 760
20241214 761
20241214 762
20241214 763
20241214 764
20241214 765
20241214 766
20241214 767
20241214 768
20241214 769
20241214 770
20241214 771
20241214 772
20241214 773
20241214 774
20241214 775
20241214 776
20241214 777
20241214 778
20241214 779
20241214 780
20241214 781
20241214 782
20241214 783
20241214 784
20241214 785
20241214 786
20241214 787
20241214 788
20241214 789
20241214 790
20241214 791
20241214 792
20241214 793
20241214 794
20241214 795
20241214 796
20241214 797
20241214 798
20241214 799
20241214 800
20241214 801
20241214 802
20241214 803
20241214 804
20241214 805
20241214 806
20241214 807
20241214 808
20241214 809
20241214 810
20241214 811
20241214 812
20241214 813
20241214 814
20241214 815
20241214 816
20241214 817
20241214 818
20241214 819
20241214 820
20241214 821
20241214 822
20241214 823
20241214 824
20241214 825
20241214 826
20241214 827
20241214 828
20241214 829
20241214 830

In [ ]:
for k in DF_XYZR.S.tolist():
  filename=home+_experiment+'/pandas/xas'
  x=DF_XYZR.loc[DF_XYZR['S']==k,'X'].values[0]
  y=DF_XYZR.loc[DF_XYZR['S']==k,'Y'].values[0]
  z=DF_XYZR.loc[DF_XYZR['S']==k,'Z'].values[0]
  r=DF_XYZR.loc[DF_XYZR['S']==k,'R'].values[0]
  angle=int(DF_XYZR.loc[DF_XYZR['S']==k,'angle'].values[0])

  _sampleid=sampleid_from_xyzr(df_sample,x,y,z,r)
  _samplename=samplename_from_xyzr(df_sample,x,y,z,r)
  if _sampleid is not None:
    if _samplename is not None:
      pass#print(_sampleid,_samplename)
    else:
      _samplename='none'
      #print(_sampleid,_samplename)
    _filename='XD_'+str(_sampleid)+'_'+str(angle)+'_XD_'+_samplename
    print(_filename)
    DF_XAS[DF_XAS.S==k].to_csv(home+_experiment+'/pandas/'+_filename+'.csv',index=False)

XD_109_0_XD_IrO2-TiO2_SL_10
XD_101_0_XD_RTO2_1
XD_101_0_XD_RTO2_1
XD_101_0_XD_RTO2_1
XD_101_0_XD_RTO2_1
XD_109_0_XD_IrO2-TiO2_SL_10
XD_105_0_XD_RTO2_5
XD_102_0_XD_RTO2_2
XD_201_0_XD_IrO2-TiO2_SL_11
XD_201_0_XD_IrO2-TiO2_SL_11
XD_209_0_XD_RuO2_421
XD_301_0_XD_RuO2_201
XD_301_0_XD_RuO2_201
XD_304_0_XD_RuO2_344
XD_107_0_XD_IrO2-TiO2_SL_08
XD_107_0_XD_IrO2-TiO2_SL_08
XD_107_0_XD_IrO2-TiO2_SL_08
XD_107_0_XD_IrO2-TiO2_SL_08
XD_107_0_XD_IrO2-TiO2_SL_08
XD_107_0_XD_IrO2-TiO2_SL_08
XD_107_0_XD_IrO2-TiO2_SL_08
XD_107_0_XD_IrO2-TiO2_SL_08
XD_101_0_XD_RTO2_1
XD_101_0_XD_RTO2_1
XD_101_0_XD_RTO2_1
XD_101_0_XD_RTO2_1
XD_102_0_XD_RTO2_2
XD_102_0_XD_RTO2_2
XD_103_0_XD_RTO2_3
XD_103_0_XD_RTO2_3
XD_104_0_XD_RTO2_4
XD_104_0_XD_RTO2_4
XD_105_0_XD_RTO2_5
XD_105_0_XD_RTO2_5
XD_106_0_XD_RTO2_6
XD_106_0_XD_RTO2_6
XD_107_0_XD_IrO2-TiO2_SL_08
XD_107_0_XD_IrO2-TiO2_SL_08
XD_108_0_XD_IrO2-TiO2_SL_09
XD_108_0_XD_IrO2-TiO2_SL_09
XD_109_0_XD_IrO2-TiO2_SL_10
XD_109_0_XD_IrO2-TiO2_SL_10
XD_101_0_XD_RTO2_1
XD_101_0_XD_RTO2_1
XD_102_0_XD_RTO2_2
XD_102_0_XD_RTO2_2
XD_103_0_XD_RTO2_3
XD_103_0_XD_RTO2_3
XD_104_0_XD_RTO2_4
XD_104_0_XD_RTO2_4
XD_105_0_XD_RTO2_5
XD_105_0_XD_RTO2_5
XD_106_0_XD_RTO2_6
XD_106_0_XD_RTO2_6
XD_107_0_XD_IrO2-TiO2_SL_08
XD_107_0_XD_IrO2-TiO2_SL_08
XD_108_0_XD_IrO2-TiO2_SL_09
XD_108_0_XD_IrO2-TiO2_SL_09
XD_109_0_XD_IrO2-TiO2_SL_10
XD_109_0_XD_IrO2-TiO2_SL_10
XD_101_0_XD_RTO2_1
XD_101_0_XD_RTO2_1
XD_102_0_XD_RTO2_2
XD_102_0_XD_RTO2_2
XD_103_0_XD_RTO2_3
XD_103_0_XD_RTO2_3
XD_104_0_XD_RTO2_4
XD_104_0_XD_RTO2_4
XD_105_0_XD_RTO2_5
XD_105_0_XD_RTO2_5
XD_106_0_XD_RTO2_6
XD_106_0_XD_RTO2_6
XD_107_0_XD_IrO2-TiO2_SL_08
XD_107_0_XD_IrO2-TiO2_SL_08
XD_108_0_XD_IrO2-TiO2_SL_09
XD_108_0_XD_IrO2-TiO2_SL_09
XD_109_0_XD_IrO2-TiO2_SL_10
XD_109_0_XD_IrO2-TiO2_SL_10
XD_101_0_XD_RTO2_1
XD_101_0_XD_RTO2_1
XD_102_0_XD_RTO2_2
XD_102_0_XD_RTO2_2
XD_103_0_XD_RTO2_3
XD_103_0_XD_RTO2_3
XD_104_0_XD_RTO2_4
XD_104_0_XD_RTO2_4
XD_105_0_XD_RTO2_5
XD_105_0_XD_RTO2_5
XD_106_0_XD_RTO2_6
XD_106_0_XD_RTO2_6
XD_107_0_XD_IrO2-TiO2_SL_08
XD_107_0_XD_IrO2-TiO2_SL_08
XD_108_0_XD_IrO2-TiO2_SL_09
XD_108_0_XD_IrO2-TiO2_SL_09
XD_109_0_XD_IrO2-TiO2_SL_10
XD_109_0_XD_IrO2-TiO2_SL_10
XD_109_0_XD_IrO2-TiO2_SL_10
XD_201_0_XD_IrO2-TiO2_SL_11
XD_201_0_XD_IrO2-TiO2_SL_11
XD_202_0_XD_IrO2-TiO2_SL_12
XD_202_0_XD_IrO2-TiO2_SL_12
XD_203_0_XD_IrO2_155
XD_203_0_XD_IrO2_155
XD_204_0_XD_IrO2_168
XD_204_0_XD_IrO2_168
XD_205_0_XD_IrO2_157
XD_205_0_XD_IrO2_157
XD_206_0_XD_IrO2_159
XD_206_0_XD_IrO2_159
XD_207_0_XD_IrO2_156
XD_207_0_XD_IrO2_156
XD_208_0_XD_IrO2_169
XD_208_0_XD_IrO2_169
XD_209_0_XD_RuO2_421
XD_209_0_XD_RuO2_421
XD_201_0_XD_IrO2-TiO2_SL_11
XD_201_0_XD_IrO2-TiO2_SL_11
XD_202_0_XD_IrO2-TiO2_SL_12
XD_202_0_XD_IrO2-TiO2_SL_12
XD_203_0_XD_IrO2_155
XD_203_0_XD_IrO2_155
XD_204_0_XD_IrO2_168
XD_204_0_XD_IrO2_168
XD_205_0_XD_IrO2_157
XD_205_0_XD_IrO2_157
XD_206_0_XD_IrO2_159
XD_206_0_XD_IrO2_159
XD_207_0_XD_IrO2_156
XD_207_0_XD_IrO2_156
XD_208_0_XD_IrO2_169
XD_208_0_XD_IrO2_169
XD_209_0_XD_RuO2_421
XD_209_0_XD_RuO2_421
XD_201_0_XD_IrO2-TiO2_SL_11
XD_201_0_XD_IrO2-TiO2_SL_11
XD_202_0_XD_IrO2-TiO2_SL_12
XD_202_0_XD_IrO2-TiO2_SL_12
XD_201_0_XD_IrO2-TiO2_SL_11
XD_201_0_XD_IrO2-TiO2_SL_11
XD_202_0_XD_IrO2-TiO2_SL_12
XD_202_0_XD_IrO2-TiO2_SL_12
XD_202_0_XD_IrO2-TiO2_SL_12
XD_301_0_XD_RuO2_201
XD_301_0_XD_RuO2_201
XD_302_0_XD_RuO2_224
XD_302_0_XD_RuO2_224
XD_303_0_XD_RuO2_356
XD_303_0_XD_RuO2_356
XD_304_0_XD_RuO2_344
XD_304_0_XD_RuO2_344
XD_301_0_XD_RuO2_201
XD_301_0_XD_RuO2_201
XD_302_0_XD_RuO2_224
XD_302_0_XD_RuO2_224
XD_303_0_XD_RuO2_356
XD_303_0_XD_RuO2_356
XD_304_0_XD_RuO2_344
XD_304_0_XD_RuO2_344
XD_101_0_XD_RTO2_1
XD_101_70_XD_RTO2_1
XD_101_70_XD_RTO2_1
XD_101_50_XD_RTO2_1
XD_101_30_XD_RTO2_1
XD_101_10_XD_RTO2_1
XD_201_70_XD_IrO2-TiO2_SL_11
XD_201_50_XD_IrO2-TiO2_SL_11
XD_201_30_XD_IrO2-TiO2_SL_11
XD_201_10_XD_IrO2-TiO2_SL_11
XD_301_70_XD_RuO2_201
XD_301_50_XD_RuO2_201
XD_301_30_XD_RuO2_201
XD_301_10_XD_RuO2_201
XD_201_50_XD_IrO2-TiO2_SL_11
XD_201_70_XD_IrO2-TiO2_SL_11
XD_201_70_XD_IrO2-TiO2_SL_11
XD_201_70_XD_IrO2-TiO2_SL_11
XD_201_70_XD_IrO2-TiO2_SL_11
XD_301_50_XD_RuO2_201
XD_301_50_XD_RuO2_201
XD_106_70_XD_RTO2_6
XD_106_70_XD_RTO2_6
XD_101_70_XD_RTO2_1
XD_101_70_XD_RTO2_1
XD_102_70_XD_RTO2_2
XD_102_70_XD_RTO2_2
XD_103_70_XD_RTO2_3
XD_103_70_XD_RTO2_3
XD_104_70_XD_RTO2_4
XD_104_70_XD_RTO2_4
XD_105_70_XD_RTO2_5
XD_105_70_XD_RTO2_5
XD_106_70_XD_RTO2_6
XD_106_70_XD_RTO2_6
XD_107_70_XD_IrO2-TiO2_SL_08
XD_107_70_XD_IrO2-TiO2_SL_08
XD_108_70_XD_IrO2-TiO2_SL_09
XD_108_70_XD_IrO2-TiO2_SL_09
XD_109_70_XD_IrO2-TiO2_SL_10
XD_109_70_XD_IrO2-TiO2_SL_10
XD_101_70_XD_RTO2_1
XD_101_70_XD_RTO2_1
XD_102_70_XD_RTO2_2
XD_102_70_XD_RTO2_2
XD_103_70_XD_RTO2_3
XD_103_70_XD_RTO2_3
XD_104_70_XD_RTO2_4
XD_104_70_XD_RTO2_4
XD_105_70_XD_RTO2_5
XD_105_70_XD_RTO2_5
XD_106_70_XD_RTO2_6
XD_106_70_XD_RTO2_6
XD_107_70_XD_IrO2-TiO2_SL_08
XD_107_70_XD_IrO2-TiO2_SL_08
XD_108_70_XD_IrO2-TiO2_SL_09
XD_108_70_XD_IrO2-TiO2_SL_09
XD_109_70_XD_IrO2-TiO2_SL_10
XD_109_70_XD_IrO2-TiO2_SL_10
XD_109_70_XD_IrO2-TiO2_SL_10
XD_201_70_XD_IrO2-TiO2_SL_11
XD_201_70_XD_IrO2-TiO2_SL_11
XD_202_70_XD_IrO2-TiO2_SL_12
XD_202_70_XD_IrO2-TiO2_SL_12
XD_203_70_XD_IrO2_155
XD_203_70_XD_IrO2_155
XD_204_70_XD_IrO2_168
XD_204_70_XD_IrO2_168
XD_205_70_XD_IrO2_157
XD_205_70_XD_IrO2_157
XD_206_70_XD_IrO2_159
XD_206_70_XD_IrO2_159
XD_207_70_XD_IrO2_156
XD_207_70_XD_IrO2_156
XD_208_70_XD_IrO2_169
XD_208_70_XD_IrO2_169
XD_209_70_XD_RuO2_421
XD_209_70_XD_RuO2_421
XD_203_70_XD_IrO2_155
XD_203_70_XD_IrO2_155
XD_204_70_XD_IrO2_168
XD_204_70_XD_IrO2_168
XD_205_70_XD_IrO2_157
XD_205_70_XD_IrO2_157
XD_206_70_XD_IrO2_159
XD_206_70_XD_IrO2_159
XD_207_70_XD_IrO2_156
XD_207_70_XD_IrO2_156
XD_208_70_XD_IrO2_169
XD_208_70_XD_IrO2_169
XD_209_70_XD_RuO2_421
XD_209_70_XD_RuO2_421
XD_201_70_XD_IrO2-TiO2_SL_11
XD_201_70_XD_IrO2-TiO2_SL_11
XD_202_70_XD_IrO2-TiO2_SL_12
XD_202_70_XD_IrO2-TiO2_SL_12
XD_202_70_XD_IrO2-TiO2_SL_12
XD_301_70_XD_RuO2_201
XD_301_70_XD_RuO2_201
XD_302_70_XD_RuO2_224
XD_302_70_XD_RuO2_224
XD_303_70_XD_RuO2_356
XD_303_70_XD_RuO2_356
XD_304_70_XD_RuO2_344
XD_304_70_XD_RuO2_344
XD_101_50_XD_RTO2_1
XD_101_50_XD_RTO2_1
XD_102_50_XD_RTO2_2
XD_102_50_XD_RTO2_2
XD_103_50_XD_RTO2_3
XD_103_50_XD_RTO2_3
XD_104_50_XD_RTO2_4
XD_104_50_XD_RTO2_4
XD_105_50_XD_RTO2_5
XD_105_50_XD_RTO2_5
XD_106_50_XD_RTO2_6
XD_106_50_XD_RTO2_6
XD_107_50_XD_IrO2-TiO2_SL_08
XD_107_50_XD_IrO2-TiO2_SL_08
XD_108_50_XD_IrO2-TiO2_SL_09
XD_108_50_XD_IrO2-TiO2_SL_09
XD_109_50_XD_IrO2-TiO2_SL_10
XD_109_50_XD_IrO2-TiO2_SL_10
XD_101_50_XD_RTO2_1
XD_101_50_XD_RTO2_1
XD_102_50_XD_RTO2_2
XD_102_50_XD_RTO2_2
XD_103_50_XD_RTO2_3
XD_103_50_XD_RTO2_3
XD_104_50_XD_RTO2_4
XD_104_50_XD_RTO2_4
XD_105_50_XD_RTO2_5
XD_105_50_XD_RTO2_5
XD_106_50_XD_RTO2_6
XD_106_50_XD_RTO2_6
XD_107_50_XD_IrO2-TiO2_SL_08
XD_107_50_XD_IrO2-TiO2_SL_08
XD_108_50_XD_IrO2-TiO2_SL_09
XD_108_50_XD_IrO2-TiO2_SL_09
XD_109_50_XD_IrO2-TiO2_SL_10
XD_109_50_XD_IrO2-TiO2_SL_10
XD_109_50_XD_IrO2-TiO2_SL_10
XD_201_50_XD_IrO2-TiO2_SL_11
XD_201_50_XD_IrO2-TiO2_SL_11
XD_202_50_XD_IrO2-TiO2_SL_12
XD_202_50_XD_IrO2-TiO2_SL_12
XD_203_50_XD_IrO2_155
XD_203_50_XD_IrO2_155
XD_204_50_XD_IrO2_168
XD_204_50_XD_IrO2_168
XD_205_50_XD_IrO2_157
XD_205_50_XD_IrO2_157
XD_206_50_XD_IrO2_159
XD_206_50_XD_IrO2_159
XD_207_50_XD_IrO2_156
XD_207_50_XD_IrO2_156
XD_208_50_XD_IrO2_169
XD_208_50_XD_IrO2_169
XD_209_50_XD_RuO2_421
XD_209_50_XD_RuO2_421
XD_203_50_XD_IrO2_155
XD_203_50_XD_IrO2_155
XD_204_50_XD_IrO2_168
XD_204_50_XD_IrO2_168
XD_205_50_XD_IrO2_157
XD_205_50_XD_IrO2_157
XD_206_50_XD_IrO2_159
XD_206_50_XD_IrO2_159
XD_207_50_XD_IrO2_156
XD_207_50_XD_IrO2_156
XD_208_50_XD_IrO2_169
XD_208_50_XD_IrO2_169
XD_209_50_XD_RuO2_421
XD_209_50_XD_RuO2_421
XD_201_50_XD_IrO2-TiO2_SL_11
XD_201_50_XD_IrO2-TiO2_SL_11
XD_202_50_XD_IrO2-TiO2_SL_12
XD_202_50_XD_IrO2-TiO2_SL_12
XD_202_50_XD_IrO2-TiO2_SL_12
XD_301_50_XD_RuO2_201
XD_301_50_XD_RuO2_201
XD_302_50_XD_RuO2_224
XD_302_50_XD_RuO2_224
XD_303_50_XD_RuO2_356
XD_303_50_XD_RuO2_356
XD_304_50_XD_RuO2_344
XD_304_50_XD_RuO2_344
XD_101_30_XD_RTO2_1
XD_101_30_XD_RTO2_1
XD_102_30_XD_RTO2_2
XD_102_30_XD_RTO2_2
XD_103_30_XD_RTO2_3
XD_103_30_XD_RTO2_3
XD_104_30_XD_RTO2_4
XD_104_30_XD_RTO2_4
XD_105_30_XD_RTO2_5
XD_105_30_XD_RTO2_5
XD_106_30_XD_RTO2_6
XD_106_30_XD_RTO2_6
XD_107_30_XD_IrO2-TiO2_SL_08
XD_107_30_XD_IrO2-TiO2_SL_08
XD_108_30_XD_IrO2-TiO2_SL_09
XD_108_30_XD_IrO2-TiO2_SL_09
XD_109_30_XD_IrO2-TiO2_SL_10
XD_109_30_XD_IrO2-TiO2_SL_10
XD_101_30_XD_RTO2_1
XD_101_30_XD_RTO2_1
XD_102_30_XD_RTO2_2
XD_102_30_XD_RTO2_2
XD_103_30_XD_RTO2_3
XD_103_30_XD_RTO2_3
XD_104_30_XD_RTO2_4
XD_104_30_XD_RTO2_4
XD_105_30_XD_RTO2_5
XD_105_30_XD_RTO2_5
XD_106_30_XD_RTO2_6
XD_106_30_XD_RTO2_6
XD_107_30_XD_IrO2-TiO2_SL_08
XD_107_30_XD_IrO2-TiO2_SL_08
XD_108_30_XD_IrO2-TiO2_SL_09
XD_108_30_XD_IrO2-TiO2_SL_09
XD_109_30_XD_IrO2-TiO2_SL_10
XD_109_30_XD_IrO2-TiO2_SL_10
XD_109_30_XD_IrO2-TiO2_SL_10
XD_201_30_XD_IrO2-TiO2_SL_11
XD_201_30_XD_IrO2-TiO2_SL_11
XD_202_30_XD_IrO2-TiO2_SL_12
XD_202_30_XD_IrO2-TiO2_SL_12
XD_203_30_XD_IrO2_155
XD_203_30_XD_IrO2_155
XD_204_30_XD_IrO2_168
XD_204_30_XD_IrO2_168
XD_205_30_XD_IrO2_157
XD_205_30_XD_IrO2_157
XD_206_30_XD_IrO2_159
XD_206_30_XD_IrO2_159
XD_207_30_XD_IrO2_156
XD_207_30_XD_IrO2_156
XD_208_30_XD_IrO2_169
XD_208_30_XD_IrO2_169
XD_209_30_XD_RuO2_421
XD_209_30_XD_RuO2_421
XD_203_30_XD_IrO2_155
XD_203_30_XD_IrO2_155
XD_204_30_XD_IrO2_168
XD_204_30_XD_IrO2_168
XD_205_30_XD_IrO2_157
XD_205_30_XD_IrO2_157
XD_206_30_XD_IrO2_159
XD_206_30_XD_IrO2_159
XD_207_30_XD_IrO2_156
XD_207_30_XD_IrO2_156
XD_208_30_XD_IrO2_169
XD_208_30_XD_IrO2_169
XD_209_30_XD_RuO2_421
XD_209_30_XD_RuO2_421
XD_201_30_XD_IrO2-TiO2_SL_11
XD_201_30_XD_IrO2-TiO2_SL_11
XD_202_30_XD_IrO2-TiO2_SL_12
XD_202_30_XD_IrO2-TiO2_SL_12
XD_202_30_XD_IrO2-TiO2_SL_12
XD_301_30_XD_RuO2_201
XD_301_30_XD_RuO2_201
XD_302_30_XD_RuO2_224
XD_302_30_XD_RuO2_224
XD_303_30_XD_RuO2_356
XD_303_30_XD_RuO2_356
XD_304_30_XD_RuO2_344
XD_304_30_XD_RuO2_344
XD_101_10_XD_RTO2_1
XD_101_10_XD_RTO2_1
XD_102_10_XD_RTO2_2
XD_102_10_XD_RTO2_2
XD_103_10_XD_RTO2_3
XD_103_10_XD_RTO2_3
XD_104_10_XD_RTO2_4
XD_104_10_XD_RTO2_4
XD_105_10_XD_RTO2_5
XD_105_10_XD_RTO2_5
XD_106_10_XD_RTO2_6
XD_106_10_XD_RTO2_6
XD_107_10_XD_IrO2-TiO2_SL_08
XD_107_10_XD_IrO2-TiO2_SL_08
XD_108_10_XD_IrO2-TiO2_SL_09
XD_108_10_XD_IrO2-TiO2_SL_09
XD_109_10_XD_IrO2-TiO2_SL_10
XD_109_10_XD_IrO2-TiO2_SL_10
XD_101_10_XD_RTO2_1
XD_101_10_XD_RTO2_1
XD_102_10_XD_RTO2_2
XD_102_10_XD_RTO2_2
XD_103_10_XD_RTO2_3
XD_103_10_XD_RTO2_3
XD_104_10_XD_RTO2_4
XD_104_10_XD_RTO2_4
XD_105_10_XD_RTO2_5
XD_105_10_XD_RTO2_5
XD_106_10_XD_RTO2_6
XD_106_10_XD_RTO2_6
XD_107_10_XD_IrO2-TiO2_SL_08
XD_107_10_XD_IrO2-TiO2_SL_08
XD_108_10_XD_IrO2-TiO2_SL_09
XD_108_10_XD_IrO2-TiO2_SL_09
XD_109_10_XD_IrO2-TiO2_SL_10
XD_109_10_XD_IrO2-TiO2_SL_10
XD_109_10_XD_IrO2-TiO2_SL_10
XD_201_10_XD_IrO2-TiO2_SL_11
XD_201_10_XD_IrO2-TiO2_SL_11
XD_202_10_XD_IrO2-TiO2_SL_12
XD_202_10_XD_IrO2-TiO2_SL_12
XD_203_10_XD_IrO2_155
XD_203_10_XD_IrO2_155
XD_204_10_XD_IrO2_168
XD_204_10_XD_IrO2_168
XD_205_10_XD_IrO2_157
XD_205_10_XD_IrO2_157
XD_206_10_XD_IrO2_159
XD_206_10_XD_IrO2_159
XD_207_10_XD_IrO2_156
XD_207_10_XD_IrO2_156
XD_208_10_XD_IrO2_169
XD_208_10_XD_IrO2_169
XD_209_10_XD_RuO2_421
XD_209_10_XD_RuO2_421
XD_203_10_XD_IrO2_155
XD_203_10_XD_IrO2_155
XD_204_10_XD_IrO2_168
XD_204_10_XD_IrO2_168
XD_205_10_XD_IrO2_157
XD_205_10_XD_IrO2_157
XD_206_10_XD_IrO2_159
XD_206_10_XD_IrO2_159
XD_207_10_XD_IrO2_156
XD_207_10_XD_IrO2_156
XD_208_10_XD_IrO2_169
XD_208_10_XD_IrO2_169
XD_209_10_XD_RuO2_421
XD_209_10_XD_RuO2_421
XD_201_10_XD_IrO2-TiO2_SL_11
XD_201_10_XD_IrO2-TiO2_SL_11
XD_202_10_XD_IrO2-TiO2_SL_12
XD_202_10_XD_IrO2-TiO2_SL_12
XD_202_10_XD_IrO2-TiO2_SL_12
XD_301_10_XD_RuO2_201
XD_301_10_XD_RuO2_201
XD_302_10_XD_RuO2_224
XD_302_10_XD_RuO2_224
XD_303_10_XD_RuO2_356
XD_303_10_XD_RuO2_356
XD_304_10_XD_RuO2_344
XD_304_10_XD_RuO2_344
XD_304_70_XD_RuO2_344
XD_101_50_XD_RTO2_1
XD_101_50_XD_RTO2_1
XD_102_50_XD_RTO2_2
XD_102_50_XD_RTO2_2
XD_103_50_XD_RTO2_3
XD_103_50_XD_RTO2_3
XD_104_50_XD_RTO2_4
XD_104_50_XD_RTO2_4
XD_105_50_XD_RTO2_5
XD_105_50_XD_RTO2_5
XD_106_50_XD_RTO2_6
XD_106_50_XD_RTO2_6
XD_107_50_XD_IrO2-TiO2_SL_08
XD_107_50_XD_IrO2-TiO2_SL_08
XD_108_50_XD_IrO2-TiO2_SL_09
XD_108_50_XD_IrO2-TiO2_SL_09
XD_109_50_XD_IrO2-TiO2_SL_10
XD_109_50_XD_IrO2-TiO2_SL_10
XD_101_50_XD_RTO2_1
XD_101_50_XD_RTO2_1
XD_102_50_XD_RTO2_2
XD_102_50_XD_RTO2_2
XD_103_50_XD_RTO2_3
XD_103_50_XD_RTO2_3
XD_104_50_XD_RTO2_4
XD_104_50_XD_RTO2_4
XD_105_50_XD_RTO2_5
XD_105_50_XD_RTO2_5
XD_106_50_XD_RTO2_6
XD_106_50_XD_RTO2_6
XD_107_50_XD_IrO2-TiO2_SL_08
XD_107_50_XD_IrO2-TiO2_SL_08
XD_108_50_XD_IrO2-TiO2_SL_09
XD_108_50_XD_IrO2-TiO2_SL_09
XD_109_50_XD_IrO2-TiO2_SL_10
XD_109_50_XD_IrO2-TiO2_SL_10
XD_109_50_XD_IrO2-TiO2_SL_10
XD_201_50_XD_IrO2-TiO2_SL_11
XD_201_50_XD_IrO2-TiO2_SL_11
XD_202_50_XD_IrO2-TiO2_SL_12
XD_202_50_XD_IrO2-TiO2_SL_12
XD_203_50_XD_IrO2_155
XD_203_50_XD_IrO2_155
XD_204_50_XD_IrO2_168
XD_204_50_XD_IrO2_168
XD_205_50_XD_IrO2_157
XD_205_50_XD_IrO2_157
XD_206_50_XD_IrO2_159
XD_206_50_XD_IrO2_159
XD_207_50_XD_IrO2_156
XD_207_50_XD_IrO2_156
XD_208_50_XD_IrO2_169
XD_208_50_XD_IrO2_169
XD_209_50_XD_RuO2_421
XD_209_50_XD_RuO2_421
XD_203_50_XD_IrO2_155
XD_203_50_XD_IrO2_155
XD_204_50_XD_IrO2_168
XD_204_50_XD_IrO2_168
XD_205_50_XD_IrO2_157
XD_205_50_XD_IrO2_157
XD_206_50_XD_IrO2_159
XD_206_50_XD_IrO2_159
XD_207_50_XD_IrO2_156
XD_207_50_XD_IrO2_156
XD_208_50_XD_IrO2_169
XD_208_50_XD_IrO2_169
XD_209_50_XD_RuO2_421
XD_209_50_XD_RuO2_421
XD_201_50_XD_IrO2-TiO2_SL_11
XD_201_50_XD_IrO2-TiO2_SL_11
XD_202_50_XD_IrO2-TiO2_SL_12
XD_202_50_XD_IrO2-TiO2_SL_12
XD_202_50_XD_IrO2-TiO2_SL_12
XD_301_50_XD_RuO2_201
XD_301_50_XD_RuO2_201
XD_302_50_XD_RuO2_224
XD_302_50_XD_RuO2_224
XD_303_50_XD_RuO2_356
XD_303_50_XD_RuO2_356
XD_304_50_XD_RuO2_344
XD_304_50_XD_RuO2_344
XD_101_30_XD_RTO2_1
XD_101_30_XD_RTO2_1
XD_102_30_XD_RTO2_2
XD_102_30_XD_RTO2_2
XD_103_30_XD_RTO2_3
XD_103_30_XD_RTO2_3
XD_104_30_XD_RTO2_4
XD_104_30_XD_RTO2_4
XD_105_30_XD_RTO2_5
XD_105_30_XD_RTO2_5
XD_106_30_XD_RTO2_6
XD_106_30_XD_RTO2_6
XD_107_30_XD_IrO2-TiO2_SL_08
XD_107_30_XD_IrO2-TiO2_SL_08
XD_108_30_XD_IrO2-TiO2_SL_09
XD_108_30_XD_IrO2-TiO2_SL_09
XD_109_30_XD_IrO2-TiO2_SL_10
XD_109_30_XD_IrO2-TiO2_SL_10
XD_101_30_XD_RTO2_1
XD_101_30_XD_RTO2_1
XD_102_30_XD_RTO2_2
XD_102_30_XD_RTO2_2
XD_103_30_XD_RTO2_3
XD_103_30_XD_RTO2_3
XD_104_30_XD_RTO2_4
XD_104_30_XD_RTO2_4
XD_105_30_XD_RTO2_5
XD_105_30_XD_RTO2_5
XD_106_30_XD_RTO2_6
XD_106_30_XD_RTO2_6
XD_107_30_XD_IrO2-TiO2_SL_08
XD_107_30_XD_IrO2-TiO2_SL_08
XD_108_30_XD_IrO2-TiO2_SL_09
XD_108_30_XD_IrO2-TiO2_SL_09
XD_109_30_XD_IrO2-TiO2_SL_10
XD_109_30_XD_IrO2-TiO2_SL_10
XD_109_30_XD_IrO2-TiO2_SL_10
XD_201_30_XD_IrO2-TiO2_SL_11
XD_201_30_XD_IrO2-TiO2_SL_11
XD_202_30_XD_IrO2-TiO2_SL_12
XD_202_30_XD_IrO2-TiO2_SL_12
XD_203_30_XD_IrO2_155
XD_203_30_XD_IrO2_155
XD_204_30_XD_IrO2_168
XD_204_30_XD_IrO2_168
XD_205_30_XD_IrO2_157
XD_205_30_XD_IrO2_157
XD_206_30_XD_IrO2_159
XD_206_30_XD_IrO2_159
XD_207_30_XD_IrO2_156
XD_207_30_XD_IrO2_156
XD_208_30_XD_IrO2_169
XD_208_30_XD_IrO2_169
XD_209_30_XD_RuO2_421
XD_209_30_XD_RuO2_421
XD_203_30_XD_IrO2_155
XD_203_30_XD_IrO2_155
XD_204_30_XD_IrO2_168
XD_204_30_XD_IrO2_168
XD_205_30_XD_IrO2_157
XD_205_30_XD_IrO2_157
XD_206_30_XD_IrO2_159
XD_206_30_XD_IrO2_159
XD_207_30_XD_IrO2_156
XD_207_30_XD_IrO2_156
XD_208_30_XD_IrO2_169
XD_208_30_XD_IrO2_169
XD_209_30_XD_RuO2_421
XD_209_30_XD_RuO2_421
XD_201_30_XD_IrO2-TiO2_SL_11
XD_201_30_XD_IrO2-TiO2_SL_11
XD_202_30_XD_IrO2-TiO2_SL_12
XD_202_30_XD_IrO2-TiO2_SL_12
XD_202_30_XD_IrO2-TiO2_SL_12
XD_301_30_XD_RuO2_201
XD_301_30_XD_RuO2_201
XD_302_30_XD_RuO2_224
XD_302_30_XD_RuO2_224
XD_303_30_XD_RuO2_356
XD_303_30_XD_RuO2_356
XD_304_30_XD_RuO2_344
XD_304_30_XD_RuO2_344
XD_304_70_XD_RuO2_344
XD_101_50_XD_RTO2_1
XD_101_50_XD_RTO2_1
XD_102_50_XD_RTO2_2
XD_102_50_XD_RTO2_2
XD_103_50_XD_RTO2_3
XD_103_50_XD_RTO2_3
XD_104_50_XD_RTO2_4
XD_104_50_XD_RTO2_4
XD_105_50_XD_RTO2_5
XD_105_50_XD_RTO2_5
XD_106_50_XD_RTO2_6
XD_106_50_XD_RTO2_6
XD_107_50_XD_IrO2-TiO2_SL_08
XD_107_50_XD_IrO2-TiO2_SL_08
XD_108_50_XD_IrO2-TiO2_SL_09
XD_108_50_XD_IrO2-TiO2_SL_09
XD_109_50_XD_IrO2-TiO2_SL_10
XD_109_50_XD_IrO2-TiO2_SL_10
XD_101_50_XD_RTO2_1
XD_101_50_XD_RTO2_1
XD_102_50_XD_RTO2_2
XD_102_50_XD_RTO2_2
XD_103_50_XD_RTO2_3
XD_103_50_XD_RTO2_3
XD_104_50_XD_RTO2_4
XD_104_50_XD_RTO2_4
XD_105_50_XD_RTO2_5
XD_105_50_XD_RTO2_5
XD_106_50_XD_RTO2_6
XD_106_50_XD_RTO2_6
XD_107_50_XD_IrO2-TiO2_SL_08
XD_107_50_XD_IrO2-TiO2_SL_08
XD_108_50_XD_IrO2-TiO2_SL_09
XD_108_50_XD_IrO2-TiO2_SL_09
XD_109_50_XD_IrO2-TiO2_SL_10
XD_109_50_XD_IrO2-TiO2_SL_10
XD_109_50_XD_IrO2-TiO2_SL_10
XD_201_50_XD_IrO2-TiO2_SL_11
XD_201_50_XD_IrO2-TiO2_SL_11
XD_202_50_XD_IrO2-TiO2_SL_12
XD_202_50_XD_IrO2-TiO2_SL_12
XD_203_50_XD_IrO2_155
XD_203_50_XD_IrO2_155
XD_204_50_XD_IrO2_168
XD_204_50_XD_IrO2_168
XD_205_50_XD_IrO2_157
XD_205_50_XD_IrO2_157
XD_206_50_XD_IrO2_159
XD_206_50_XD_IrO2_159
XD_207_50_XD_IrO2_156
XD_207_50_XD_IrO2_156
XD_208_50_XD_IrO2_169
XD_208_50_XD_IrO2_169
XD_209_50_XD_RuO2_421
XD_209_50_XD_RuO2_421
XD_203_50_XD_IrO2_155
XD_203_50_XD_IrO2_155
XD_204_50_XD_IrO2_168
XD_204_50_XD_IrO2_168
XD_205_50_XD_IrO2_157
XD_205_50_XD_IrO2_157
XD_206_50_XD_IrO2_159
XD_206_50_XD_IrO2_159
XD_207_50_XD_IrO2_156
XD_207_50_XD_IrO2_156
XD_208_50_XD_IrO2_169
XD_208_50_XD_IrO2_169
XD_209_50_XD_RuO2_421
XD_209_50_XD_RuO2_421
XD_201_50_XD_IrO2-TiO2_SL_11
XD_201_50_XD_IrO2-TiO2_SL_11
XD_202_50_XD_IrO2-TiO2_SL_12
XD_202_50_XD_IrO2-TiO2_SL_12
XD_202_50_XD_IrO2-TiO2_SL_12
XD_301_50_XD_RuO2_201
XD_301_50_XD_RuO2_201
XD_302_50_XD_RuO2_224
XD_302_50_XD_RuO2_224
XD_303_50_XD_RuO2_356
XD_303_50_XD_RuO2_356
XD_304_50_XD_RuO2_344
XD_304_50_XD_RuO2_344
XD_101_30_XD_RTO2_1
XD_101_30_XD_RTO2_1
XD_102_30_XD_RTO2_2
XD_102_30_XD_RTO2_2
XD_103_30_XD_RTO2_3
XD_103_30_XD_RTO2_3
XD_104_30_XD_RTO2_4
XD_104_30_XD_RTO2_4
XD_105_30_XD_RTO2_5
XD_105_30_XD_RTO2_5
XD_106_30_XD_RTO2_6
XD_106_30_XD_RTO2_6
XD_107_30_XD_IrO2-TiO2_SL_08
XD_107_30_XD_IrO2-TiO2_SL_08
XD_108_30_XD_IrO2-TiO2_SL_09
XD_108_30_XD_IrO2-TiO2_SL_09
XD_109_30_XD_IrO2-TiO2_SL_10
XD_109_30_XD_IrO2-TiO2_SL_10
XD_101_30_XD_RTO2_1
XD_101_30_XD_RTO2_1
XD_102_30_XD_RTO2_2
XD_102_30_XD_RTO2_2
XD_103_30_XD_RTO2_3
XD_103_30_XD_RTO2_3
XD_104_30_XD_RTO2_4
XD_104_30_XD_RTO2_4
XD_105_30_XD_RTO2_5
XD_105_30_XD_RTO2_5
XD_106_30_XD_RTO2_6
XD_106_30_XD_RTO2_6
XD_107_30_XD_IrO2-TiO2_SL_08
XD_107_30_XD_IrO2-TiO2_SL_08
XD_108_30_XD_IrO2-TiO2_SL_09
XD_108_30_XD_IrO2-TiO2_SL_09
XD_109_30_XD_IrO2-TiO2_SL_10
XD_109_30_XD_IrO2-TiO2_SL_10
XD_109_30_XD_IrO2-TiO2_SL_10
XD_201_30_XD_IrO2-TiO2_SL_11
XD_201_30_XD_IrO2-TiO2_SL_11
XD_202_30_XD_IrO2-TiO2_SL_12
XD_202_30_XD_IrO2-TiO2_SL_12
XD_203_30_XD_IrO2_155
XD_203_30_XD_IrO2_155
XD_204_30_XD_IrO2_168
XD_204_30_XD_IrO2_168
XD_205_30_XD_IrO2_157
XD_205_30_XD_IrO2_157
XD_206_30_XD_IrO2_159
XD_206_30_XD_IrO2_159
XD_207_30_XD_IrO2_156
XD_207_30_XD_IrO2_156
XD_208_30_XD_IrO2_169
XD_208_30_XD_IrO2_169
XD_209_30_XD_RuO2_421
XD_209_30_XD_RuO2_421
XD_203_30_XD_IrO2_155
XD_203_30_XD_IrO2_155
XD_201_10_XD_IrO2-TiO2_SL_11
XD_201_30_XD_IrO2-TiO2_SL_11
XD_201_30_XD_IrO2-TiO2_SL_11
XD_202_30_XD_IrO2-TiO2_SL_12
XD_202_30_XD_IrO2-TiO2_SL_12
XD_301_30_XD_RuO2_201
XD_301_30_XD_RuO2_201
XD_302_30_XD_RuO2_224
XD_302_30_XD_RuO2_224
XD_303_30_XD_RuO2_356
XD_303_30_XD_RuO2_356
XD_304_30_XD_RuO2_344
XD_304_30_XD_RuO2_344

# Export XAS DF

## Reload XAS daraframe

In [ ]:
#LOAD
inputfile=dir+'/pandas/df_xas.csv'
DF_XAS=pd.read_csv(inputfile)

In [ ]:
for k in  DF_XYZR.S.unique().tolist():
  if k>0:
    XAS=DF_XAS[DF_XAS['S']==k][["mono132","MONO132","SCAN","SC","I0","ID","S"]]
    _samplename=samplename_from_id(df_sample,XAS[XAS['S']==k].ID.values[0])
    _sampleid=XAS[XAS['S']==k].ID.values[0]
    #filters=[_samplename,"'mono132' in XAS[XAS['S']==k].SCAN.values[0]","(XAS[XAS['S']==k].I0.values[0] >10"]
    #filterstring=' and '.join(filters)
    #print(filterstring)
    _angle=int(DF_XYZR[DF_XYZR['S']==k]['angle'].values[0])
    if _samplename and ("mono132" in XAS[XAS['S']==k].SCAN.values[0]) and (XAS[XAS['S']==k].I0.values[0] >10) and (XAS[XAS['S']==k].I0.values[0] >10) and (_angle>0):
        #print(_sampleid,_samplename)

      #print(_sampleid,_samplename)
        _scanstring=scanstring_from_mono132(XAS[XAS['S']==k].MONO132.unique())
      #print(k,_samplename,_scanstring)
        belowedge=normlow_from_scanstring(_scanstring)
        aboveedge=normhigh_from_scanstring(_scanstring)
    #print(belowedge,aboveedge)
  #Y=DF_XYZR[DF_XYZR['S']==k]
        belowedge=(((XAS[(XAS.mono132>=belowedge[0]) & (XAS.mono132<=belowedge[1])].SC)/(XAS[(XAS.mono132>=belowedge[0]) & (XAS.mono132<=belowedge[1])].I0))).mean()#.mono132
        aboveip=(((XAS[(XAS.mono132>=aboveedge[0]) & (XAS.mono132<=aboveedge[1])].SC)/(XAS[(XAS.mono132>=aboveedge[0]) & (XAS.mono132<=aboveedge[1])].I0))).mean()#.mono132
    #print(belowedge,aboveip)
        xas_x=XAS.mono132
        xas_i0=XAS.I0
        xas_tey=XAS.SC
        xas_y=XAS.SC/XAS.I0
      #xas_y_norm=(XAS.SC/XAS.I0-belowedge)/aboveip
        filename='o7_'+str(k)+'_'+_scanstring+'_'+str(_sampleid)+'_'+str(_angle)+'_o7_'+_samplename
        plt.title(filename)
        plt.plot(xas_x,xas_y,label=_samplename+' '+str(_angle))
      #plt.plot(xas_x,xas_y_norm,label=str(k+' '+_angle+' '+_samplename
        plt.legend(loc="upper right")
    #print(k)
        plt.show()
        concatenated_df=pd.concat([xas_x,xas_y,xas_i0,xas_tey])
        concatenated_df.to_csv(dir+_filename+'.csv',index=False)